### ISSUE TITLE
Value and Pointer Receivers

### ISSUE THREAD

**Issue by ColonelBlimp** [PylotLight/wails-vite-svelte-tailwind-template#1]
Many thanks for this template. It made scaffolding a svelte and tailwindcss app really easy.

I did notice one thing:

In `app.go` the function:

**func (a App) domReady(ctx context.Context) {
    // Add your action here
}**

I believe it should be:

**func (a \*App) domReady(ctx context.Context) {
    // Add your action here
}**

I understand that it is not recommended that a Go struct has some receivers which return a value and others a pointer?

**Comment by PylotLight** [comment]
This is from default wails2 templates meaning I didn't touch any of this for my template. So that's all up to you. Feel free to join the discord for discussion on that.
